name: flutter_calculator
description: A Flutter Calculator built by DigitalHonor.org

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.2

  # Update the version of cupertino_icons to a null-safe version
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: "lib/assets/calc.png"

flutter:
  uses-material-design: true
